application: mugin
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /
  script: mugin.app

#The Handler to the front page which requires login
- url: /mugin
  script: mugin.app
  login: required

# All other pages does not necessarily require login
- url: /.*
  script: mugin.app
  login: optional

libraries:
- name: jinja2
  version: latest