application: muginnus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /_ah/login_required
  script: muginnus.app

# Handler for front page
- url: /
  script: muginnus.app

#The Handler to the pages which requires login
- url: /info/*
  script: muginnus.app
  login: required

- url: /chats
  script: muginnus.app
  login: required

# All other pages does not necessarily require login
- url: /.*
  script: muginnus.app
  login: optional

libraries:
- name: jinja2
  version: latest